name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Install dependencies
        working-directory: ./04_Practice_Project
        run: npm ci
      - name: Lint code
        working-directory: ./04_Practice_Project
        run: npm run lint
      - name: Test code
        working-directory: ./04_Practice_Project
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file:  ${{steps.publish.outputs.script-file}}
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Install dependencies
        working-directory: ./04_Practice_Project
        run: npm ci
      - name: Build website
        working-directory: ./04_Practice_Project
        run: npm run build

      - name: Publish JS filename
        id: publish # this ID is used to reference outputs from this step in the outpus script-file above
        run: find ./04_Practice_Project/dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';' # Writes output to a file in the GITHUB_OUTPUT path
      
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          #mandatory field
          path: ./04_Practice_Project/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: List dist-files
        run: ls 
      - name: Output file name
          #needs is used to reference outputs from previous jobs
        run: echo "${{ needs.build.outputs.script-file}}"
      - name: Deploy
        run: echo "Deploying..."
